/**
 * ListAuditPack DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAuditPacksParams } from "@splitward/core/audit-packs";

export function createListAuditPackRequest(overrides: Partial<ListAuditPacksParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
