/**
 * Handlers for Incident
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IncidentsDomainModule } from "../dependencies/incidents-ddd.dependencies.js";
import type { GetIncidentInput, ListIncidentsInput, OpenIncidentInput } from "@splitward/services/incidents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/incidents
 * Operation: listIncidents
 */
export async function listIncidents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListIncidentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.incidents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/incidents
 * Operation: openIncident
 */
export async function openIncident(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenIncidentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.incidents.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/incidents/{incidentId}
 * Operation: getIncident
 */
export async function getIncident(
  request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetIncidentInput = {
    incidentId: request.params.incidentId,
  };
  const result = await deps.useCases.incidents.get.execute(input);
  return reply.code(200).send(result);
}


