/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * ModelReleases Domain Use Cases
 * 
 * List of all use case names for the model-releases domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const MODELRELEASES_USE_CASES = [
  "executeClinicalSignOffModelRelease",
  "executeCreateModelRelease",
  "executeGetModelRelease",
  "executeListModelReleases"
] as const;
