/**
 * Repository interface for ModelRelease
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ModelReleaseEntity
} from "../models/model-release.entity.js";
import type {
  ListModelReleasesParams,
  ModelRelease
} from "../types/index.js";
/**
 * ModelReleaseRepository Interface
 */
export interface ModelReleaseRepository extends CreateReadRepository<ModelReleaseEntity, ModelRelease, string, ListModelReleasesParams> {

}
