/**
 * RightsExclusions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsExclusions Domain Module - Composition root
 *
 * DDD: Composition root for rights-exclusions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttestRepositoryAdapter,
  RightsExclusionRepositoryAdapter,
} from "@splitward/adapters/rights-exclusions";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateRightsExclusion,
  ExecuteGetRightsExclusion,
  ExecuteListRightsExclusions,
} from "@splitward/services/rights-exclusions/usecases";
// Ports (interfaces)
import type {
  AttestRepository,
  RightsExclusionRepository,
} from "@splitward/services/rights-exclusions/ports";

export interface RightsExclusionsDomainModule {
  repos: {
    attests: AttestRepository;
    rightsExclusions: RightsExclusionRepository;
  };
  useCases: {
    rightsExclusions: {
      create: ExecuteCreateRightsExclusion;
      get: ExecuteGetRightsExclusion;
      list: ExecuteListRightsExclusions;
    };
  };
}

export function buildRightsExclusionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RightsExclusionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attests?: AttestRepository;
      rightsExclusions?: RightsExclusionRepository;
    } = {};

    obj.attests = new AttestRepositoryAdapter(dynamoClient);
    obj.rightsExclusions = new RightsExclusionRepositoryAdapter(dynamoClient);
    return {
      attests: obj.attests!,
      rightsExclusions: obj.rightsExclusions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    rightsExclusions: {
      create: new ExecuteCreateRightsExclusion(executionContext, idGenerator, repos.rightsExclusions),
      get: new ExecuteGetRightsExclusion(executionContext, idGenerator, repos.rightsExclusions),
      list: new ExecuteListRightsExclusions(executionContext, idGenerator, repos.rightsExclusions),
    },
  };
  return { repos, useCases: useCases as RightsExclusionsDomainModule["useCases"] };
}
