/**
 * AuditPack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AuditPackEntity } from "@splitward/core/audit-packs/models/index.js";
import { auditPacksSchemas } from "@splitward/core/audit-packs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "aud";

export function createAuditPack(overrides: Partial<AuditPackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    packId: overrides.packId ?? `aud_${ulid().toLowerCase()}`,
    periodEnd: overrides.periodEnd ?? new Date().toISOString(),
    periodStart: overrides.periodStart ?? new Date().toISOString(),
    status: overrides.status ?? "pending",
    studyId: overrides.studyId ?? faker.string.uuid(),
    ...overrides,
  };

  return auditPacksSchemas.AuditPack.parse(raw);
}

export function auditPackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAuditPack(overrides));
}
