/**
 * Study DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Study DTOs
 *
 * DDD: Application DTOs for Study use cases.
 */

import type { CreateStudyRequestInput, GetStudyParams, ListStudiesParams } from "@splitward/core/studies/types";

export type ListStudiesInput = ListStudiesParams;

export type CreateStudyInput = CreateStudyRequestInput;

export type GetStudyInput = GetStudyParams;

export type ListStudiesOutput = {};

export type CreateStudyOutput = {};

export type GetStudyOutput = {};
