/**
 * SubmitPrivacy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitPrivacy DTOs
 *
 * DDD: Application DTOs for SubmitPrivacy use cases.
 */

import type { SubmitStudyForPrivacyParams, SubmitStudyForPrivacyRequestInput } from "@splitward/core/studies/types";

export type SubmitStudyForPrivacyInput = SubmitStudyForPrivacyParams & SubmitStudyForPrivacyRequestInput;

export type SubmitStudyForPrivacyOutput = {};
