/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * RightsExclusions Domain Use Cases
 * 
 * List of all use case names for the rights-exclusions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const RIGHTSEXCLUSIONS_USE_CASES = [
  "executeAttestRightsExclusion",
  "executeCreateRightsExclusion",
  "executeGetRightsExclusion",
  "executeListRightsExclusions"
] as const;
