/**
 * Incidents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Incidents Domain Module - Composition root
 *
 * DDD: Composition root for incidents domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  HaltStudyRepositoryAdapter,
  IncidentRepositoryAdapter,
} from "@splitward/adapters/incidents";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetIncident,
  ExecuteListIncidents,
  ExecuteOpenIncident,
} from "@splitward/services/incidents/usecases";
// Ports (interfaces)
import type {
  HaltStudyRepository,
  IncidentRepository,
} from "@splitward/services/incidents/ports";

export interface IncidentsDomainModule {
  repos: {
    haltStudies: HaltStudyRepository;
    incidents: IncidentRepository;
  };
  useCases: {
    incidents: {
      get: ExecuteGetIncident;
      list: ExecuteListIncidents;
    };
  };
}

export function buildIncidentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): IncidentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      haltStudies?: HaltStudyRepository;
      incidents?: IncidentRepository;
    } = {};

    obj.haltStudies = new HaltStudyRepositoryAdapter(dynamoClient);
    obj.incidents = new IncidentRepositoryAdapter(dynamoClient);
    return {
      haltStudies: obj.haltStudies!,
      incidents: obj.incidents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    incidents: {
      get: new ExecuteGetIncident(executionContext, idGenerator, repos.incidents),
      list: new ExecuteListIncidents(executionContext, idGenerator, repos.incidents),
    },
  };
  return { repos, useCases: useCases as IncidentsDomainModule["useCases"] };
}
