/**
 * GetContributionCredit handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getContributionCredit } from "@splitward/api-server/domains/contribution-credits/handlers";
import type { ContributionCreditsDDDDependencies } from "@splitward/api-server/domains/contribution-credits";
import { createContributionCredit as createContributionCreditEntity } from "@splitward/factories/contribution-credits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { CONTRIBUTIONCREDITS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetContributionCredit", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContributionCreditsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContributionCreditsDDDDependencies>(
      CONTRIBUTIONCREDITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createContributionCreditEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetContributionCredit, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { creditId: entity.id };

    await getContributionCredit(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetContributionCredit.execute).toHaveBeenCalledWith(expect.objectContaining({ creditId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { creditId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetContributionCredit, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getContributionCredit(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
