/**
 * RightsExclusion Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/rights-exclusions.openapi.types.js";
import { schemas } from "../schemas/rights-exclusions.schemas.js";

/**
 * Entity: RightsExclusionEntity
 * Description: Represents the RightsExclusion domain model.
 * Source: schemas.RightsExclusion
 * Type: Domain Entity (API)
 */
export const RightsExclusionEntitySchema = schemas.RightsExclusion;
export type RightsExclusionEntity = components["schemas"]["RightsExclusion"];
