/**
 * ModelRelease Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ModelReleaseEntity } from "@splitward/core/model-releases/models/index.js";
import { modelReleasesSchemas } from "@splitward/core/model-releases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rel";

export function createModelRelease(overrides: Partial<ModelReleaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    releaseId: overrides.releaseId ?? `rel_${ulid().toLowerCase()}`,
    status: overrides.status ?? "candidate",
    studyId: overrides.studyId ?? faker.string.uuid(),
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return modelReleasesSchemas.ModelRelease.parse(raw);
}

export function modelReleaseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createModelRelease(overrides));
}
