/**
 * ExecuteOpenIncident - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenIncident Use Case
 *
 * DDD: Application use case for get Incident.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenIncidentInput, OpenIncidentOutput } from "../dto/incident.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { IncidentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenIncident {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly incident: IncidentRepository
  ) {}

  async execute(input: OpenIncidentInput): Promise<OpenIncidentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: detail, incidentType, severity, studyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).studyId) {
      throw new ValidationError("studyId is required");
    }
    const studyId = (input as any).studyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.incident.openIncident({ studyId: studyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${studyId}`);
    }

    return entity as OpenIncidentOutput;
  }
}
