/**
 * Studies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Studies Domain Module - Composition root
 *
 * DDD: Composition root for studies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApprovePrivacyRepositoryAdapter,
  StudyRepositoryAdapter,
  SubmitPrivacyRepositoryAdapter,
} from "@splitward/adapters/studies";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateStudy,
  ExecuteGetStudy,
  ExecuteListStudies,
} from "@splitward/services/studies/usecases";
// Ports (interfaces)
import type {
  ApprovePrivacyRepository,
  StudyRepository,
  SubmitPrivacyRepository,
} from "@splitward/services/studies/ports";

export interface StudiesDomainModule {
  repos: {
    approvePrivacies: ApprovePrivacyRepository;
    studies: StudyRepository;
    submitPrivacies: SubmitPrivacyRepository;
  };
  useCases: {
    studies: {
      create: ExecuteCreateStudy;
      get: ExecuteGetStudy;
      list: ExecuteListStudies;
    };
  };
}

export function buildStudiesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): StudiesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approvePrivacies?: ApprovePrivacyRepository;
      studies?: StudyRepository;
      submitPrivacies?: SubmitPrivacyRepository;
    } = {};

    obj.approvePrivacies = new ApprovePrivacyRepositoryAdapter(dynamoClient);
    obj.studies = new StudyRepositoryAdapter(dynamoClient);
    obj.submitPrivacies = new SubmitPrivacyRepositoryAdapter(dynamoClient);
    return {
      approvePrivacies: obj.approvePrivacies!,
      studies: obj.studies!,
      submitPrivacies: obj.submitPrivacies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    studies: {
      create: new ExecuteCreateStudy(executionContext, idGenerator, repos.studies),
      get: new ExecuteGetStudy(executionContext, idGenerator, repos.studies),
      list: new ExecuteListStudies(executionContext, idGenerator, repos.studies),
    },
  };
  return { repos, useCases: useCases as StudiesDomainModule["useCases"] };
}
