/**
 * ContributionCredits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionCredits Domain Module - Composition root
 *
 * DDD: Composition root for contribution-credits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ContributionCreditRepositoryAdapter,
} from "@splitward/adapters/contribution-credits";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetContributionCredit,
  ExecuteListContributionCredits,
  ExecuteRecordContributionCredit,
} from "@splitward/services/contribution-credits/usecases";
// Ports (interfaces)
import type {
  ContributionCreditRepository,
} from "@splitward/services/contribution-credits/ports";

export interface ContributionCreditsDomainModule {
  repos: {
    contributionCredits: ContributionCreditRepository;
  };
  useCases: {
    contributionCredits: {
      get: ExecuteGetContributionCredit;
      list: ExecuteListContributionCredits;
    };
  };
}

export function buildContributionCreditsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ContributionCreditsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      contributionCredits?: ContributionCreditRepository;
    } = {};

    obj.contributionCredits = new ContributionCreditRepositoryAdapter(dynamoClient);
    return {
      contributionCredits: obj.contributionCredits!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    contributionCredits: {
      get: new ExecuteGetContributionCredit(executionContext, idGenerator, repos.contributionCredits),
      list: new ExecuteListContributionCredits(executionContext, idGenerator, repos.contributionCredits),
    },
  };
  return { repos, useCases: useCases as ContributionCreditsDomainModule["useCases"] };
}
