/**
 * Handlers for TrainingRound
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrainingRoundsDomainModule } from "../dependencies/training-rounds-ddd.dependencies.js";
import type { GetTrainingRoundInput, ListTrainingRoundsInput, StartTrainingRoundInput } from "@splitward/services/training-rounds";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/training-rounds
 * Operation: listTrainingRounds
 */
export async function listTrainingRounds(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TrainingRoundsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTrainingRoundsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.trainingRounds.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/training-rounds
 * Operation: startTrainingRound
 */
export async function startTrainingRound(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TrainingRoundsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: StartTrainingRoundInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.trainingRounds.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/training-rounds/{roundId}
 * Operation: getTrainingRound
 */
export async function getTrainingRound(
  request: FastifyRequest<{ Params: { roundId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrainingRoundsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetTrainingRoundInput = {
    roundId: request.params.roundId,
  };
  const result = await deps.useCases.trainingRounds.get.execute(input);
  return reply.code(200).send(result);
}


