/**
 * Handlers for Study
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StudiesDomainModule } from "../dependencies/studies-ddd.dependencies.js";
import type { CreateStudyInput, GetStudyInput, ListStudiesInput } from "@splitward/services/studies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/studies
 * Operation: listStudies
 */
export async function listStudies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: StudiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListStudiesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.studies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/studies
 * Operation: createStudy
 */
export async function createStudy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: StudiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateStudyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.studies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/studies/{studyId}
 * Operation: getStudy
 */
export async function getStudy(
  request: FastifyRequest<{ Params: { studyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StudiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetStudyInput = {
    studyId: request.params.studyId,
  };
  const result = await deps.useCases.studies.get.execute(input);
  return reply.code(200).send(result);
}


