/**
 * ContributionCredit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionCredit DTOs
 *
 * DDD: Application DTOs for ContributionCredit use cases.
 */

import type { GetContributionCreditParams, ListContributionCreditsParams, RecordContributionCreditRequestInput } from "@splitward/core/contribution-credits/types";

export type ListContributionCreditsInput = ListContributionCreditsParams;

export type RecordContributionCreditInput = RecordContributionCreditRequestInput;

export type GetContributionCreditInput = GetContributionCreditParams;

export type ListContributionCreditsOutput = {};

export type RecordContributionCreditOutput = {};

export type GetContributionCreditOutput = {};
