/**
 * AttestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttestRepository Port
 *
 * DDD: Application port for attestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttestRightsExclusionInput, AttestRightsExclusionOutput } from "../dto/attest.dto";
export interface AttestRepository {
  attestRightsExclusion(input: AttestRightsExclusionInput): Promise<AttestRightsExclusionOutput>;
}

export type { AttestRightsExclusionInput, AttestRightsExclusionOutput } from "../dto/attest.dto";
