/**
 * RightsExclusionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsExclusionRepository Port
 *
 * DDD: Application port for rightsexclusionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRightsExclusionInput, CreateRightsExclusionOutput, GetRightsExclusionInput, GetRightsExclusionOutput, ListRightsExclusionsInput, ListRightsExclusionsOutput } from "../dto/rights-exclusion.dto";
export interface RightsExclusionRepository {
  listRightsExclusions(input: ListRightsExclusionsInput): Promise<ListRightsExclusionsOutput>;
  createRightsExclusion(input: CreateRightsExclusionInput): Promise<CreateRightsExclusionOutput>;
  getRightsExclusion(input: GetRightsExclusionInput): Promise<GetRightsExclusionOutput>;
}

export type { CreateRightsExclusionInput, CreateRightsExclusionOutput, GetRightsExclusionInput, GetRightsExclusionOutput, ListRightsExclusionsInput, ListRightsExclusionsOutput } from "../dto/rights-exclusion.dto";
