/**
 * RightsExclusionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsExclusionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RightsExclusionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RightsExclusionRepository,
} from "@splitward/services/rights-exclusions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RightsExclusionRepositoryDdb } from "./rights-exclusion-repository.ddb.js";

/**
 * RightsExclusionRepositoryAdapter
 *
 * Implements RightsExclusionRepository port for infrastructure layer.
 */
export class RightsExclusionRepositoryAdapter implements RightsExclusionRepository {
  private readonly ddb: RightsExclusionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RightsExclusionRepositoryDdb(this.dynamoClient);
  }

  async listRightsExclusions(input: Parameters<RightsExclusionRepository['listRightsExclusions']>[0]): Promise<Awaited<ReturnType<RightsExclusionRepository['listRightsExclusions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRightsExclusions(input);
  }

  async createRightsExclusion(input: Parameters<RightsExclusionRepository['createRightsExclusion']>[0]): Promise<Awaited<ReturnType<RightsExclusionRepository['createRightsExclusion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createRightsExclusion(input);
  }

  async getRightsExclusion(input: Parameters<RightsExclusionRepository['getRightsExclusion']>[0]): Promise<Awaited<ReturnType<RightsExclusionRepository['getRightsExclusion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRightsExclusion(input);
  }
}
