/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as auditPacksRoutes from "../../domains/audit-packs/routes/index.js";
import * as contributionCreditsRoutes from "../../domains/contribution-credits/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as incidentsRoutes from "../../domains/incidents/routes/index.js";
import * as localDatasetsRoutes from "../../domains/local-datasets/routes/index.js";
import * as modelReleasesRoutes from "../../domains/model-releases/routes/index.js";
import * as rightsExclusionsRoutes from "../../domains/rights-exclusions/routes/index.js";
import * as sitesRoutes from "../../domains/sites/routes/index.js";
import * as studiesRoutes from "../../domains/studies/routes/index.js";
import * as trainingRoundsRoutes from "../../domains/training-rounds/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "audit-packs", mod: auditPacksRoutes },
  { domain: "contribution-credits", mod: contributionCreditsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "incidents", mod: incidentsRoutes },
  { domain: "local-datasets", mod: localDatasetsRoutes },
  { domain: "model-releases", mod: modelReleasesRoutes },
  { domain: "rights-exclusions", mod: rightsExclusionsRoutes },
  { domain: "sites", mod: sitesRoutes },
  { domain: "studies", mod: studiesRoutes },
  { domain: "training-rounds", mod: trainingRoundsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
