/**
 * HaltStudy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HaltStudy DTOs
 *
 * DDD: Application DTOs for HaltStudy use cases.
 */

import type { HaltStudyForIncidentParams, HaltStudyForIncidentRequestInput } from "@splitward/core/incidents/types";

export type HaltStudyForIncidentInput = HaltStudyForIncidentParams & HaltStudyForIncidentRequestInput;

export type HaltStudyForIncidentOutput = {};
