/**
 * Incident DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Incident DTOs
 *
 * DDD: Application DTOs for Incident use cases.
 */

import type { GetIncidentParams, ListIncidentsParams, OpenIncidentRequestInput } from "@splitward/core/incidents/types";

export type ListIncidentsInput = ListIncidentsParams;

export type OpenIncidentInput = OpenIncidentRequestInput;

export type GetIncidentInput = GetIncidentParams;

export type ListIncidentsOutput = {};

export type OpenIncidentOutput = {};

export type GetIncidentOutput = {};
