/**
 * ModelReleases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelReleases Domain Module - Composition root
 *
 * DDD: Composition root for model-releases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ClinicalSignoffRepositoryAdapter,
  ModelReleaseRepositoryAdapter,
} from "@splitward/adapters/model-releases";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateModelRelease,
  ExecuteGetModelRelease,
  ExecuteListModelReleases,
} from "@splitward/services/model-releases/usecases";
// Ports (interfaces)
import type {
  ClinicalSignoffRepository,
  ModelReleaseRepository,
} from "@splitward/services/model-releases/ports";

export interface ModelReleasesDomainModule {
  repos: {
    clinicalSignoffs: ClinicalSignoffRepository;
    modelReleases: ModelReleaseRepository;
  };
  useCases: {
    modelReleases: {
      create: ExecuteCreateModelRelease;
      get: ExecuteGetModelRelease;
      list: ExecuteListModelReleases;
    };
  };
}

export function buildModelReleasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ModelReleasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      clinicalSignoffs?: ClinicalSignoffRepository;
      modelReleases?: ModelReleaseRepository;
    } = {};

    obj.clinicalSignoffs = new ClinicalSignoffRepositoryAdapter(dynamoClient);
    obj.modelReleases = new ModelReleaseRepositoryAdapter(dynamoClient);
    return {
      clinicalSignoffs: obj.clinicalSignoffs!,
      modelReleases: obj.modelReleases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    modelReleases: {
      create: new ExecuteCreateModelRelease(executionContext, idGenerator, repos.modelReleases),
      get: new ExecuteGetModelRelease(executionContext, idGenerator, repos.modelReleases),
      list: new ExecuteListModelReleases(executionContext, idGenerator, repos.modelReleases),
    },
  };
  return { repos, useCases: useCases as ModelReleasesDomainModule["useCases"] };
}
