/**
 * ExecuteGetAuditPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAuditPack Use Case
 *
 * DDD: Application use case for get AuditPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAuditPackInput, GetAuditPackOutput } from "../dto/audit-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { AuditPackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAuditPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly auditPack: AuditPackRepository
  ) {}

  async execute(input: GetAuditPackInput): Promise<GetAuditPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).packId) {
      throw new ValidationError("packId is required");
    }
    const packId = (input as any).packId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.auditPack.getAuditPack({ packId: packId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${packId}`);
    }

    return entity as GetAuditPackOutput;
  }
}
