/**
 * ExecuteListAuditPacks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAuditPacks Use Case
 *
 * DDD: Application use case for list AuditPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAuditPacksInput, ListAuditPacksOutput } from "../dto/audit-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { AuditPackRepository } from "../ports";

export class ExecuteListAuditPacks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly auditPack: AuditPackRepository
  ) {}

  async execute(input: ListAuditPacksInput): Promise<ListAuditPacksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.auditPack.listAuditPacks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAuditPacksOutput;
  }
}
