/**
 * ListRightsExclusion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRightsExclusionsParams } from "@splitward/core/rights-exclusions";

export function createListRightsExclusionRequest(overrides: Partial<ListRightsExclusionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
