/**
 * TrainingRound DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrainingRound DTOs
 *
 * DDD: Application DTOs for TrainingRound use cases.
 */

import type { GetTrainingRoundParams, ListTrainingRoundsParams, StartTrainingRoundRequestInput } from "@splitward/core/training-rounds/types";

export type ListTrainingRoundsInput = ListTrainingRoundsParams;

export type StartTrainingRoundInput = StartTrainingRoundRequestInput;

export type GetTrainingRoundInput = GetTrainingRoundParams;

export type ListTrainingRoundsOutput = {};

export type StartTrainingRoundOutput = {};

export type GetTrainingRoundOutput = {};
