/**
 * HaltStudyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HaltStudyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HaltStudyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HaltStudyRepository,
} from "@splitward/services/incidents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HaltStudyRepositoryDdb } from "./halt-study-repository.ddb.js";

/**
 * HaltStudyRepositoryAdapter
 *
 * Implements HaltStudyRepository port for infrastructure layer.
 */
export class HaltStudyRepositoryAdapter implements HaltStudyRepository {
  private readonly ddb: HaltStudyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HaltStudyRepositoryDdb(this.dynamoClient);
  }

  async haltStudyForIncident(input: Parameters<HaltStudyRepository['haltStudyForIncident']>[0]): Promise<Awaited<ReturnType<HaltStudyRepository['haltStudyForIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.haltStudyForIncident(input);
  }
}
