/**
 * Studies Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createStudy_Body = z
  .object({
    title: z.string().min(1).max(200),
    strategy: z.enum(['split', 'federated', 'hybrid']),
    activationTtlHours: z.number().int().gte(1).optional(),
    participantSiteIds: z.array(z.string()).optional(),
    marketHookEnabled: z.boolean().optional(),
    purpose: z.string().max(2000).optional(),
  })
  .passthrough();
const submitStudyForPrivacy_Body = z
  .object({ ethicsRefs: z.array(z.string()), notes: z.string().max(2000) })
  .partial()
  .passthrough();
const approveStudyPrivacy_Body = z
  .object({
    decision: z.enum(['approved', 'rejected']),
    reason: z.string().max(2000).optional(),
  })
  .passthrough();

export const schemas: any = {
  createStudy_Body,
  submitStudyForPrivacy_Body,
  approveStudyPrivacy_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v0/tenants/me/studies',
    alias: 'listStudies',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  studyId: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
                  title: z.string().min(1).max(200),
                  strategy: z.enum(['split', 'federated', 'hybrid']),
                  status: z.enum([
                    'draft',
                    'pendingPrivacy',
                    'approved',
                    'running',
                    'halted',
                    'completed',
                  ]),
                  privacyApprovalStatus: z.enum([
                    'pending',
                    'approved',
                    'rejected',
                  ]),
                  activationTtlHours: z.number().int().gte(1).optional(),
                  participantSiteIds: z.array(z.string()).optional(),
                  marketHookEnabled: z.boolean().optional(),
                  purpose: z.string().max(2000).optional(),
                  createdAt: z.string().datetime({ offset: true }).optional(),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/tenants/me/studies',
    alias: 'createStudy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createStudy_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            studyId: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            strategy: z.enum(['split', 'federated', 'hybrid']),
            status: z.enum([
              'draft',
              'pendingPrivacy',
              'approved',
              'running',
              'halted',
              'completed',
            ]),
            privacyApprovalStatus: z.enum(['pending', 'approved', 'rejected']),
            activationTtlHours: z.number().int().gte(1).optional(),
            participantSiteIds: z.array(z.string()).optional(),
            marketHookEnabled: z.boolean().optional(),
            purpose: z.string().max(2000).optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v0/tenants/me/studies/:studyId',
    alias: 'getStudy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'studyId',
        type: 'Path',
        schema: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            studyId: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            strategy: z.enum(['split', 'federated', 'hybrid']),
            status: z.enum([
              'draft',
              'pendingPrivacy',
              'approved',
              'running',
              'halted',
              'completed',
            ]),
            privacyApprovalStatus: z.enum(['pending', 'approved', 'rejected']),
            activationTtlHours: z.number().int().gte(1).optional(),
            participantSiteIds: z.array(z.string()).optional(),
            marketHookEnabled: z.boolean().optional(),
            purpose: z.string().max(2000).optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/tenants/me/studies/:studyId/approve-privacy',
    alias: 'approveStudyPrivacy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: approveStudyPrivacy_Body.optional(),
      },
      {
        name: 'studyId',
        type: 'Path',
        schema: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            studyId: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            strategy: z.enum(['split', 'federated', 'hybrid']),
            status: z.enum([
              'draft',
              'pendingPrivacy',
              'approved',
              'running',
              'halted',
              'completed',
            ]),
            privacyApprovalStatus: z.enum(['pending', 'approved', 'rejected']),
            activationTtlHours: z.number().int().gte(1).optional(),
            participantSiteIds: z.array(z.string()).optional(),
            marketHookEnabled: z.boolean().optional(),
            purpose: z.string().max(2000).optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/tenants/me/studies/:studyId/submit-privacy',
    alias: 'submitStudyForPrivacy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: submitStudyForPrivacy_Body.optional(),
      },
      {
        name: 'studyId',
        type: 'Path',
        schema: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            studyId: z.string().regex(/^stu_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            strategy: z.enum(['split', 'federated', 'hybrid']),
            status: z.enum([
              'draft',
              'pendingPrivacy',
              'approved',
              'running',
              'halted',
              'completed',
            ]),
            privacyApprovalStatus: z.enum(['pending', 'approved', 'rejected']),
            activationTtlHours: z.number().int().gte(1).optional(),
            participantSiteIds: z.array(z.string()).optional(),
            marketHookEnabled: z.boolean().optional(),
            purpose: z.string().max(2000).optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
