/**
 * ClinicalSignOffModelRelease handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { clinicalSignOffModelRelease } from "@splitward/api-server/domains/model-releases/handlers";
import type { ModelReleasesDDDDependencies } from "@splitward/api-server/domains/model-releases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { MODELRELEASES_USE_CASES } from "../__factories__/use-cases.js";

describe("ClinicalSignOffModelRelease", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelReleasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelReleasesDDDDependencies>(
      MODELRELEASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeClinicalSignOffModelRelease, "execute").mockResolvedValue(useCaseResult);

    await clinicalSignOffModelRelease(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeClinicalSignOffModelRelease.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
