/**
 * RightsExclusion DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsExclusion DTOs
 *
 * DDD: Application DTOs for RightsExclusion use cases.
 */

import type { CreateRightsExclusionRequestInput, GetRightsExclusionParams, ListRightsExclusionsParams } from "@splitward/core/rights-exclusions/types";

export type ListRightsExclusionsInput = ListRightsExclusionsParams;

export type CreateRightsExclusionInput = CreateRightsExclusionRequestInput;

export type GetRightsExclusionInput = GetRightsExclusionParams;

export type ListRightsExclusionsOutput = {};

export type CreateRightsExclusionOutput = {};

export type GetRightsExclusionOutput = {};
