/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { approvePrivacyRoutes } from "./approve-privacy.routes.js";
export { studyRoutes } from "./study.routes.js";
export { submitPrivacyRoutes } from "./submit-privacy.routes.js";
