/**
 * Routes for Study
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createStudy, getStudy, listStudies } from "../handlers/study.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function studyRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/studies (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/studies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStudiesDependenciesForRequest();
        await createStudy(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/studies (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/studies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStudiesDependenciesForRequest();
        await listStudies(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/studies/{studyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/studies/:studyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { studyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStudiesDependenciesForRequest();
        await getStudy(request, reply, deps);
      });
    }
  );


}
