/**
 * TrainingRounds Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const startTrainingRound_Body = z
  .object({
    studyId: z.string(),
    roundNumber: z.number().int().gte(1),
    sitesExpected: z.number().int().gte(1),
    stragglerTimeoutSec: z.number().int().gte(1),
    partialAggregationAllowed: z.boolean().optional(),
  })
  .passthrough();

export const schemas: any = {
  startTrainingRound_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v0/tenants/me/training-rounds',
    alias: 'listTrainingRounds',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  roundId: z.string().regex(/^rnd_[0-9A-HJKMNP-TV-Z]{26}$/),
                  studyId: z.string(),
                  roundNumber: z.number().int().gte(1),
                  status: z.enum([
                    'pending',
                    'running',
                    'succeeded',
                    'partial',
                    'failed',
                    'halted',
                  ]),
                  sitesExpected: z.number().int().gte(1),
                  sitesCompleted: z.number().int().gte(0),
                  stragglerTimeoutSec: z.number().int().gte(1),
                  partialAggregationAllowed: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }).optional(),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/tenants/me/training-rounds',
    alias: 'startTrainingRound',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: startTrainingRound_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            roundId: z.string().regex(/^rnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            studyId: z.string(),
            roundNumber: z.number().int().gte(1),
            status: z.enum([
              'pending',
              'running',
              'succeeded',
              'partial',
              'failed',
              'halted',
            ]),
            sitesExpected: z.number().int().gte(1),
            sitesCompleted: z.number().int().gte(0),
            stragglerTimeoutSec: z.number().int().gte(1),
            partialAggregationAllowed: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v0/tenants/me/training-rounds/:roundId',
    alias: 'getTrainingRound',
    requestFormat: 'json',
    parameters: [
      {
        name: 'roundId',
        type: 'Path',
        schema: z.string().regex(/^rnd_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            roundId: z.string().regex(/^rnd_[0-9A-HJKMNP-TV-Z]{26}$/),
            studyId: z.string(),
            roundNumber: z.number().int().gte(1),
            status: z.enum([
              'pending',
              'running',
              'succeeded',
              'partial',
              'failed',
              'halted',
            ]),
            sitesExpected: z.number().int().gte(1),
            sitesCompleted: z.number().int().gte(0),
            stragglerTimeoutSec: z.number().int().gte(1),
            partialAggregationAllowed: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
