/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @splitward/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@splitward/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@splitward/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@splitward/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@splitward/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@splitward/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _auditPacks from "./audit-packs/index.js";
import * as _contributionCredits from "./contribution-credits/index.js";
import * as _identity from "./identity/index.js";
import * as _incidents from "./incidents/index.js";
import * as _localDatasets from "./local-datasets/index.js";
import * as _modelReleases from "./model-releases/index.js";
import * as _rightsExclusions from "./rights-exclusions/index.js";
import * as _sites from "./sites/index.js";
import * as _studies from "./studies/index.js";
import * as _trainingRounds from "./training-rounds/index.js";

// Export as namespaces
export const _shared = __shared;
export const auditPacks = _auditPacks;
export const contributionCredits = _contributionCredits;
export const identity = _identity;
export const incidents = _incidents;
export const localDatasets = _localDatasets;
export const modelReleases = _modelReleases;
export const rightsExclusions = _rightsExclusions;
export const sites = _sites;
export const studies = _studies;
export const trainingRounds = _trainingRounds;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@splitward/core"; activity.types.*
//   - Direct exports: import * from "@splitward/core/activity/types/index.js"
//   - Direct exports: import * from "@splitward/core/activity/repositories/index.js"
//   - Direct exports: import * from "@splitward/core/activity/models/index.js"
//   - Direct exports: import * from "@splitward/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// AuditPacks Service
export { schemas as AuditPacksSchemas } from "./audit-packs/schemas/audit-packs.schemas.js";

// ContributionCredits Service
export { schemas as ContributionCreditsSchemas } from "./contribution-credits/schemas/contribution-credits.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Incidents Service
export { schemas as IncidentsSchemas } from "./incidents/schemas/incidents.schemas.js";

// LocalDatasets Service
export { schemas as LocalDatasetsSchemas } from "./local-datasets/schemas/local-datasets.schemas.js";

// ModelReleases Service
export { schemas as ModelReleasesSchemas } from "./model-releases/schemas/model-releases.schemas.js";

// RightsExclusions Service
export { schemas as RightsExclusionsSchemas } from "./rights-exclusions/schemas/rights-exclusions.schemas.js";

// Sites Service
export { schemas as SitesSchemas } from "./sites/schemas/sites.schemas.js";

// Studies Service
export { schemas as StudiesSchemas } from "./studies/schemas/studies.schemas.js";

// TrainingRounds Service
export { schemas as TrainingRoundsSchemas } from "./training-rounds/schemas/training-rounds.schemas.js";

