/**
 * TrainingRound Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/training-rounds.openapi.types.js";
import { schemas } from "../schemas/training-rounds.schemas.js";

/**
 * Entity: TrainingRoundEntity
 * Description: Represents the TrainingRound domain model.
 * Source: schemas.TrainingRound
 * Type: Domain Entity (API)
 */
export const TrainingRoundEntitySchema = schemas.TrainingRound;
export type TrainingRoundEntity = components["schemas"]["TrainingRound"];
