/**
 * ContributionCredit Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ContributionCreditEntity } from "@splitward/core/contribution-credits/models/index.js";
import { contributionCreditsSchemas } from "@splitward/core/contribution-credits";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "crd";

export function createContributionCredit(overrides: Partial<ContributionCreditEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    creditId: overrides.creditId ?? `crd_${ulid().toLowerCase()}`,
    dataVolumeClass: overrides.dataVolumeClass ?? "S",
    roundsCompleted: overrides.roundsCompleted ?? faker.number.int(),
    siteId: overrides.siteId ?? faker.string.uuid(),
    studyId: overrides.studyId ?? faker.string.uuid(),
    ...overrides,
  };

  return contributionCreditsSchemas.ContributionCredit.parse(raw);
}

export function contributionCreditBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createContributionCredit(overrides));
}
