/**
 * GenerateAuditPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { generateAuditPack } from "@splitward/api-server/domains/audit-packs/handlers";
import type { AuditPacksDDDDependencies } from "@splitward/api-server/domains/audit-packs";
import { createAuditPack as createAuditPackEntity } from "@splitward/factories/audit-packs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { AUDITPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GenerateAuditPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditPacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditPacksDDDDependencies>(
      AUDITPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAuditPackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeGenerateAuditPack, "execute").mockResolvedValue(useCaseResult);

    await generateAuditPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGenerateAuditPack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
