/**
 * GetAuditPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAuditPack } from "@splitward/api-server/domains/audit-packs/handlers";
import type { AuditPacksDDDDependencies } from "@splitward/api-server/domains/audit-packs";
import { createAuditPack as createAuditPackEntity } from "@splitward/factories/audit-packs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { AUDITPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAuditPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditPacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditPacksDDDDependencies>(
      AUDITPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAuditPackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAuditPack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { packId: entity.id };

    await getAuditPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAuditPack.execute).toHaveBeenCalledWith(expect.objectContaining({ packId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { packId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAuditPack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAuditPack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
