/**
 * ListAuditPacks handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAuditPacks } from "@splitward/api-server/domains/audit-packs/handlers";
import type { AuditPacksDDDDependencies } from "@splitward/api-server/domains/audit-packs";
import { createAuditPack as createAuditPackEntity } from "@splitward/factories/audit-packs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { AUDITPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAuditPacks", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditPacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditPacksDDDDependencies>(
      AUDITPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAuditPackEntity({ orgId }),
      createAuditPackEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAuditPacks, "execute").mockResolvedValue(useCaseResult);

    await listAuditPacks(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAuditPacks.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
