/**
 * Incident Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IncidentEntity } from "@splitward/core/incidents/models/index.js";
import { incidentsSchemas } from "@splitward/core/incidents";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inc";

export function createIncident(overrides: Partial<IncidentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    incidentId: overrides.incidentId ?? `inc_${ulid().toLowerCase()}`,
    incidentType: overrides.incidentType ?? "suspectedLeakage",
    severity: overrides.severity ?? "low",
    status: overrides.status ?? "open",
    studyId: overrides.studyId ?? faker.string.uuid(),
    ...overrides,
  };

  return incidentsSchemas.Incident.parse(raw);
}

export function incidentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIncident(overrides));
}
