/**
 * Repository interface for ContributionCredit
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ContributionCreditEntity
} from "../models/contribution-credit.entity.js";
import type {
  ListContributionCreditsParams,
  ContributionCredit
} from "../types/index.js";
/**
 * ContributionCreditRepository Interface
 */
export interface ContributionCreditRepository extends CreateReadRepository<ContributionCreditEntity, ContributionCredit, string, ListContributionCreditsParams> {

}
