/**
 * CreateModelRelease handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createModelRelease } from "@splitward/api-server/domains/model-releases/handlers";
import type { ModelReleasesDDDDependencies } from "@splitward/api-server/domains/model-releases";
import { createModelRelease as createModelReleaseEntity } from "@splitward/factories/model-releases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { MODELRELEASES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateModelRelease", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelReleasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelReleasesDDDDependencies>(
      MODELRELEASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createModelReleaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateModelRelease, "execute").mockResolvedValue(useCaseResult);

    await createModelRelease(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateModelRelease.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
