/**
 * GetModelRelease handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getModelRelease } from "@splitward/api-server/domains/model-releases/handlers";
import type { ModelReleasesDDDDependencies } from "@splitward/api-server/domains/model-releases";
import { createModelRelease as createModelReleaseEntity } from "@splitward/factories/model-releases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { MODELRELEASES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetModelRelease", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelReleasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelReleasesDDDDependencies>(
      MODELRELEASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createModelReleaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetModelRelease, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { releaseId: entity.id };

    await getModelRelease(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetModelRelease.execute).toHaveBeenCalledWith(expect.objectContaining({ releaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { releaseId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetModelRelease, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getModelRelease(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
