/**
 * ListModelReleases handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listModelReleases } from "@splitward/api-server/domains/model-releases/handlers";
import type { ModelReleasesDDDDependencies } from "@splitward/api-server/domains/model-releases";
import { createModelRelease as createModelReleaseEntity } from "@splitward/factories/model-releases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { MODELRELEASES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListModelReleases", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelReleasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelReleasesDDDDependencies>(
      MODELRELEASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createModelReleaseEntity({ orgId }),
      createModelReleaseEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListModelReleases, "execute").mockResolvedValue(useCaseResult);

    await listModelReleases(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListModelReleases.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
