/**
 * ExecuteGetStudy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetStudy Use Case
 *
 * DDD: Application use case for get Study.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetStudyInput, GetStudyOutput } from "../dto/study.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { StudyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetStudy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly study: StudyRepository
  ) {}

  async execute(input: GetStudyInput): Promise<GetStudyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stuId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).studyId) {
      throw new ValidationError("studyId is required");
    }
    const studyId = (input as any).studyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.study.getStudy({ studyId: studyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${studyId}`);
    }

    return entity as GetStudyOutput;
  }
}
