/**
 * ContributionCredit Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/contribution-credits.openapi.types.js";
import { schemas } from "../schemas/contribution-credits.schemas.js";

/**
 * Entity: ContributionCreditEntity
 * Description: Represents the ContributionCredit domain model.
 * Source: schemas.ContributionCredit
 * Type: Domain Entity (API)
 */
export const ContributionCreditEntitySchema = schemas.ContributionCredit;
export type ContributionCreditEntity = components["schemas"]["ContributionCredit"];
