/**
 * GetTrainingRound DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTrainingRoundParams } from "@splitward/core/training-rounds";

export function createGetTrainingRoundRequest(overrides: Partial<GetTrainingRoundParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
