/**
 * ClinicalSignoffRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClinicalSignoffRepository Port
 *
 * DDD: Application port for clinicalsignoffrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClinicalSignOffModelReleaseInput, ClinicalSignOffModelReleaseOutput } from "../dto/clinical-signoff.dto";
export interface ClinicalSignoffRepository {
  clinicalSignOffModelRelease(input: ClinicalSignOffModelReleaseInput): Promise<ClinicalSignOffModelReleaseOutput>;
}

export type { ClinicalSignOffModelReleaseInput, ClinicalSignOffModelReleaseOutput } from "../dto/clinical-signoff.dto";
