/**
 * ModelReleaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelReleaseRepository Port
 *
 * DDD: Application port for modelreleaserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateModelReleaseInput, CreateModelReleaseOutput, GetModelReleaseInput, GetModelReleaseOutput, ListModelReleasesInput, ListModelReleasesOutput } from "../dto/model-release.dto";
export interface ModelReleaseRepository {
  listModelReleases(input: ListModelReleasesInput): Promise<ListModelReleasesOutput>;
  createModelRelease(input: CreateModelReleaseInput): Promise<CreateModelReleaseOutput>;
  getModelRelease(input: GetModelReleaseInput): Promise<GetModelReleaseOutput>;
}

export type { CreateModelReleaseInput, CreateModelReleaseOutput, GetModelReleaseInput, GetModelReleaseOutput, ListModelReleasesInput, ListModelReleasesOutput } from "../dto/model-release.dto";
