/**
 * ExecuteRecordContributionCredit - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordContributionCredit Use Case
 *
 * DDD: Application use case for get ContributionCredit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordContributionCreditInput, RecordContributionCreditOutput } from "../dto/contribution-credit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { ContributionCreditRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordContributionCredit {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contributionCredit: ContributionCreditRepository
  ) {}

  async execute(input: RecordContributionCreditInput): Promise<RecordContributionCreditOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crdId();

    // All field names extracted from OpenAPI spec: creditPoints, dataVolumeClass, roundsCompleted, siteId, studyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).siteId) {
      throw new ValidationError("siteId is required");
    }
    const siteId = (input as any).siteId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.contributionCredit.recordContributionCredit({ siteId: siteId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${siteId}`);
    }

    return entity as RecordContributionCreditOutput;
  }
}
