/**
 * ExecuteListContributionCredits - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListContributionCredits Use Case
 *
 * DDD: Application use case for list ContributionCredit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListContributionCreditsInput, ListContributionCreditsOutput } from "../dto/contribution-credit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { ContributionCreditRepository } from "../ports";

export class ExecuteListContributionCredits {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contributionCredit: ContributionCreditRepository
  ) {}

  async execute(input: ListContributionCreditsInput): Promise<ListContributionCreditsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.contributionCredit.listContributionCredits({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListContributionCreditsOutput;
  }
}
