/**
 * HaltStudyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HaltStudyRepository Port
 *
 * DDD: Application port for haltstudyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { HaltStudyForIncidentInput, HaltStudyForIncidentOutput } from "../dto/halt-study.dto";
export interface HaltStudyRepository {
  haltStudyForIncident(input: HaltStudyForIncidentInput): Promise<HaltStudyForIncidentOutput>;
}

export type { HaltStudyForIncidentInput, HaltStudyForIncidentOutput } from "../dto/halt-study.dto";
