/**
 * CreateRightsExclusion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createRightsExclusion } from "@splitward/api-server/domains/rights-exclusions/handlers";
import type { RightsExclusionsDDDDependencies } from "@splitward/api-server/domains/rights-exclusions";
import { createRightsExclusion as createRightsExclusionEntity } from "@splitward/factories/rights-exclusions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { RIGHTSEXCLUSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateRightsExclusion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RightsExclusionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RightsExclusionsDDDDependencies>(
      RIGHTSEXCLUSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createRightsExclusionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateRightsExclusion, "execute").mockResolvedValue(useCaseResult);

    await createRightsExclusion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateRightsExclusion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
