/**
 * GetRightsExclusion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRightsExclusion } from "@splitward/api-server/domains/rights-exclusions/handlers";
import type { RightsExclusionsDDDDependencies } from "@splitward/api-server/domains/rights-exclusions";
import { createRightsExclusion as createRightsExclusionEntity } from "@splitward/factories/rights-exclusions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { RIGHTSEXCLUSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRightsExclusion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RightsExclusionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RightsExclusionsDDDDependencies>(
      RIGHTSEXCLUSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRightsExclusionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRightsExclusion, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { exclusionId: entity.id };

    await getRightsExclusion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRightsExclusion.execute).toHaveBeenCalledWith(expect.objectContaining({ exclusionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { exclusionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRightsExclusion, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRightsExclusion(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
