/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-rights-exclusion.handler.test.js";
export * from "./get-rights-exclusion.handler.test.js";
export * from "./list-rights-exclusions.handler.test.js";
