/**
 * Handlers for AuditPack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AuditPacksDomainModule } from "../dependencies/audit-packs-ddd.dependencies.js";
import type { GenerateAuditPackInput, GetAuditPackInput, ListAuditPacksInput } from "@splitward/services/audit-packs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/audit-packs
 * Operation: listAuditPacks
 */
export async function listAuditPacks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditPacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAuditPacksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.auditPacks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/audit-packs
 * Operation: generateAuditPack
 */
export async function generateAuditPack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AuditPacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GenerateAuditPackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.auditPacks.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/audit-packs/{packId}
 * Operation: getAuditPack
 */
export async function getAuditPack(
  request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditPacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAuditPackInput = {
    packId: request.params.packId,
  };
  const result = await deps.useCases.auditPacks.get.execute(input);
  return reply.code(200).send(result);
}


