/**
 * ClinicalSignoffRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClinicalSignoffRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ClinicalSignoffRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ClinicalSignoffRepository,
} from "@splitward/services/model-releases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ClinicalSignoffRepositoryDdb } from "./clinical-signoff-repository.ddb.js";

/**
 * ClinicalSignoffRepositoryAdapter
 *
 * Implements ClinicalSignoffRepository port for infrastructure layer.
 */
export class ClinicalSignoffRepositoryAdapter implements ClinicalSignoffRepository {
  private readonly ddb: ClinicalSignoffRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ClinicalSignoffRepositoryDdb(this.dynamoClient);
  }

  async clinicalSignOffModelRelease(input: Parameters<ClinicalSignoffRepository['clinicalSignOffModelRelease']>[0]): Promise<Awaited<ReturnType<ClinicalSignoffRepository['clinicalSignOffModelRelease']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.clinicalSignOffModelRelease(input);
  }
}
