/**
 * ModelReleaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelReleaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ModelReleaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ModelReleaseRepository,
} from "@splitward/services/model-releases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ModelReleaseRepositoryDdb } from "./model-release-repository.ddb.js";

/**
 * ModelReleaseRepositoryAdapter
 *
 * Implements ModelReleaseRepository port for infrastructure layer.
 */
export class ModelReleaseRepositoryAdapter implements ModelReleaseRepository {
  private readonly ddb: ModelReleaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ModelReleaseRepositoryDdb(this.dynamoClient);
  }

  async listModelReleases(input: Parameters<ModelReleaseRepository['listModelReleases']>[0]): Promise<Awaited<ReturnType<ModelReleaseRepository['listModelReleases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelReleases(input);
  }

  async createModelRelease(input: Parameters<ModelReleaseRepository['createModelRelease']>[0]): Promise<Awaited<ReturnType<ModelReleaseRepository['createModelRelease']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createModelRelease(input);
  }

  async getModelRelease(input: Parameters<ModelReleaseRepository['getModelRelease']>[0]): Promise<Awaited<ReturnType<ModelReleaseRepository['getModelRelease']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModelRelease(input);
  }
}
