/**
 * TrainingRoundRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrainingRoundRepository Port
 *
 * DDD: Application port for trainingroundrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTrainingRoundInput, GetTrainingRoundOutput, ListTrainingRoundsInput, ListTrainingRoundsOutput, StartTrainingRoundInput, StartTrainingRoundOutput } from "../dto/training-round.dto";
export interface TrainingRoundRepository {
  listTrainingRounds(input: ListTrainingRoundsInput): Promise<ListTrainingRoundsOutput>;
  startTrainingRound(input: StartTrainingRoundInput): Promise<StartTrainingRoundOutput>;
  getTrainingRound(input: GetTrainingRoundInput): Promise<GetTrainingRoundOutput>;
}

export type { GetTrainingRoundInput, GetTrainingRoundOutput, ListTrainingRoundsInput, ListTrainingRoundsOutput, StartTrainingRoundInput, StartTrainingRoundOutput } from "../dto/training-round.dto";
