/**
 * TrainingRoundRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrainingRoundRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TrainingRoundRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TrainingRoundRepository,
} from "@splitward/services/training-rounds";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TrainingRoundRepositoryDdb } from "./training-round-repository.ddb.js";

/**
 * TrainingRoundRepositoryAdapter
 *
 * Implements TrainingRoundRepository port for infrastructure layer.
 */
export class TrainingRoundRepositoryAdapter implements TrainingRoundRepository {
  private readonly ddb: TrainingRoundRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TrainingRoundRepositoryDdb(this.dynamoClient);
  }

  async listTrainingRounds(input: Parameters<TrainingRoundRepository['listTrainingRounds']>[0]): Promise<Awaited<ReturnType<TrainingRoundRepository['listTrainingRounds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTrainingRounds(input);
  }

  async startTrainingRound(input: Parameters<TrainingRoundRepository['startTrainingRound']>[0]): Promise<Awaited<ReturnType<TrainingRoundRepository['startTrainingRound']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.startTrainingRound(input);
  }

  async getTrainingRound(input: Parameters<TrainingRoundRepository['getTrainingRound']>[0]): Promise<Awaited<ReturnType<TrainingRoundRepository['getTrainingRound']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTrainingRound(input);
  }
}
