/**
 * GetContributionCredit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetContributionCreditParams } from "@splitward/core/contribution-credits";

export function createGetContributionCreditRequest(overrides: Partial<GetContributionCreditParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
