/**
 * ClinicalSignoff DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClinicalSignoff DTOs
 *
 * DDD: Application DTOs for ClinicalSignoff use cases.
 */

import type { ClinicalSignOffModelReleaseParams, ClinicalSignOffModelReleaseRequestInput } from "@splitward/core/model-releases/types";

export type ClinicalSignOffModelReleaseInput = ClinicalSignOffModelReleaseParams & ClinicalSignOffModelReleaseRequestInput;

export type ClinicalSignOffModelReleaseOutput = {};
