/**
 * ModelRelease DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelRelease DTOs
 *
 * DDD: Application DTOs for ModelRelease use cases.
 */

import type { CreateModelReleaseRequestInput, GetModelReleaseParams, ListModelReleasesParams } from "@splitward/core/model-releases/types";

export type ListModelReleasesInput = ListModelReleasesParams;

export type CreateModelReleaseInput = CreateModelReleaseRequestInput;

export type GetModelReleaseInput = GetModelReleaseParams;

export type ListModelReleasesOutput = {};

export type CreateModelReleaseOutput = {};

export type GetModelReleaseOutput = {};
