/**
 * ExecuteGetModelRelease - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetModelRelease Use Case
 *
 * DDD: Application use case for get ModelRelease.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetModelReleaseInput, GetModelReleaseOutput } from "../dto/model-release.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { ModelReleaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetModelRelease {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly modelRelease: ModelReleaseRepository
  ) {}

  async execute(input: GetModelReleaseInput): Promise<GetModelReleaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.relId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).releaseId) {
      throw new ValidationError("releaseId is required");
    }
    const releaseId = (input as any).releaseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.modelRelease.getModelRelease({ releaseId: releaseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${releaseId}`);
    }

    return entity as GetModelReleaseOutput;
  }
}
