/**
 * ExecuteCreateModelRelease - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateModelRelease Use Case
 *
 * DDD: Application use case for create ModelRelease.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateModelReleaseInput, CreateModelReleaseOutput } from "../dto/model-release.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { ModelReleaseRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateModelRelease {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly modelRelease: ModelReleaseRepository
  ) {}

  async execute(input: CreateModelReleaseInput): Promise<CreateModelReleaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.relId();

    // All field names extracted from OpenAPI spec: metricsSummary, studyId, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.studyId) {
      throw new ValidationError("studyId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (model-releases domain)
    const entityId = this.idGenerator.relId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.modelRelease.createModelRelease({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateModelReleaseOutput;
  }
}
