/**
 * ExecuteStartTrainingRound - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteStartTrainingRound Use Case
 *
 * DDD: Application use case for create TrainingRound.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { StartTrainingRoundInput, StartTrainingRoundOutput } from "../dto/training-round.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { TrainingRoundRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteStartTrainingRound {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trainingRound: TrainingRoundRepository
  ) {}

  async execute(input: StartTrainingRoundInput): Promise<StartTrainingRoundOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rndId();

    // All field names extracted from OpenAPI spec: partialAggregationAllowed, roundNumber, sitesExpected, stragglerTimeoutSec, studyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.studyId) {
      throw new ValidationError("studyId is required");
    }
    if (!input.roundNumber) {
      throw new ValidationError("roundNumber is required");
    }
    if (!input.stragglerTimeoutSec) {
      throw new ValidationError("stragglerTimeoutSec is required");
    }
    if (!input.sitesExpected) {
      throw new ValidationError("sitesExpected is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (training-rounds domain)
    const entityId = this.idGenerator.rndId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.trainingRound.startTrainingRound({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as StartTrainingRoundOutput;
  }
}
