/**
 * ExecuteGetTrainingRound - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTrainingRound Use Case
 *
 * DDD: Application use case for get TrainingRound.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTrainingRoundInput, GetTrainingRoundOutput } from "../dto/training-round.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { TrainingRoundRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetTrainingRound {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trainingRound: TrainingRoundRepository
  ) {}

  async execute(input: GetTrainingRoundInput): Promise<GetTrainingRoundOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rndId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).roundId) {
      throw new ValidationError("roundId is required");
    }
    const roundId = (input as any).roundId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.trainingRound.getTrainingRound({ roundId: roundId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${roundId}`);
    }

    return entity as GetTrainingRoundOutput;
  }
}
