/**
 * Handlers for RightsExclusion
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RightsExclusionsDomainModule } from "../dependencies/rights-exclusions-ddd.dependencies.js";
import type { CreateRightsExclusionInput, GetRightsExclusionInput, ListRightsExclusionsInput } from "@splitward/services/rights-exclusions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/rights-exclusions
 * Operation: listRightsExclusions
 */
export async function listRightsExclusions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RightsExclusionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRightsExclusionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.rightsExclusions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/rights-exclusions
 * Operation: createRightsExclusion
 */
export async function createRightsExclusion(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: RightsExclusionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRightsExclusionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rightsExclusions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/rights-exclusions/{exclusionId}
 * Operation: getRightsExclusion
 */
export async function getRightsExclusion(
  request: FastifyRequest<{ Params: { exclusionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RightsExclusionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRightsExclusionInput = {
    exclusionId: request.params.exclusionId,
  };
  const result = await deps.useCases.rightsExclusions.get.execute(input);
  return reply.code(200).send(result);
}


