/**
 * ExecuteGetRightsExclusion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRightsExclusion Use Case
 *
 * DDD: Application use case for get RightsExclusion.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRightsExclusionInput, GetRightsExclusionOutput } from "../dto/rights-exclusion.dto";
import type { ExecutionContextService, IdGeneratorService } from "@splitward/services/_shared/index.js";
import type { RightsExclusionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRightsExclusion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rightsExclusion: RightsExclusionRepository
  ) {}

  async execute(input: GetRightsExclusionInput): Promise<GetRightsExclusionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rexId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).exclusionId) {
      throw new ValidationError("exclusionId is required");
    }
    const exclusionId = (input as any).exclusionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rightsExclusion.getRightsExclusion({ exclusionId: exclusionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${exclusionId}`);
    }

    return entity as GetRightsExclusionOutput;
  }
}
