/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * AuditPacks Domain Use Cases
 * 
 * List of all use case names for the audit-packs domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const AUDITPACKS_USE_CASES = [
  "executeGenerateAuditPack",
  "executeGetAuditPack",
  "executeListAuditPacks"
] as const;
