/**
 * GetIncident handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getIncident } from "@splitward/api-server/domains/incidents/handlers";
import type { IncidentsDDDDependencies } from "@splitward/api-server/domains/incidents";
import { createIncident as createIncidentEntity } from "@splitward/factories/incidents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { INCIDENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetIncident", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IncidentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IncidentsDDDDependencies>(
      INCIDENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createIncidentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetIncident, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { incidentId: entity.id };

    await getIncident(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetIncident.execute).toHaveBeenCalledWith(expect.objectContaining({ incidentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { incidentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetIncident, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getIncident(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
