/**
 * ApprovePrivacyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApprovePrivacyRepository Port
 *
 * DDD: Application port for approveprivacyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApproveStudyPrivacyInput, ApproveStudyPrivacyOutput } from "../dto/approve-privacy.dto";
export interface ApprovePrivacyRepository {
  approveStudyPrivacy(input: ApproveStudyPrivacyInput): Promise<ApproveStudyPrivacyOutput>;
}

export type { ApproveStudyPrivacyInput, ApproveStudyPrivacyOutput } from "../dto/approve-privacy.dto";
