/**
 * StudyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StudyRepository Port
 *
 * DDD: Application port for studyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateStudyInput, CreateStudyOutput, GetStudyInput, GetStudyOutput, ListStudiesInput, ListStudiesOutput } from "../dto/study.dto";
export interface StudyRepository {
  listStudies(input: ListStudiesInput): Promise<ListStudiesOutput>;
  createStudy(input: CreateStudyInput): Promise<CreateStudyOutput>;
  getStudy(input: GetStudyInput): Promise<GetStudyOutput>;
}

export type { CreateStudyInput, CreateStudyOutput, GetStudyInput, GetStudyOutput, ListStudiesInput, ListStudiesOutput } from "../dto/study.dto";
