/**
 * SubmitPrivacyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitPrivacyRepository Port
 *
 * DDD: Application port for submitprivacyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitStudyForPrivacyInput, SubmitStudyForPrivacyOutput } from "../dto/submit-privacy.dto";
export interface SubmitPrivacyRepository {
  submitStudyForPrivacy(input: SubmitStudyForPrivacyInput): Promise<SubmitStudyForPrivacyOutput>;
}

export type { SubmitStudyForPrivacyInput, SubmitStudyForPrivacyOutput } from "../dto/submit-privacy.dto";
