/**
 * Handlers for ClinicalSignoff
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelReleasesDomainModule } from "../dependencies/model-releases-ddd.dependencies.js";
import type { ClinicalSignOffModelReleaseInput } from "@splitward/services/model-releases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/tenants/me/model-releases/{releaseId}/clinical-signoff
 * Operation: clinicalSignOffModelRelease
 */
export async function clinicalSignOffModelRelease(
  request: FastifyRequest<{ Params: { releaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelReleasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ClinicalSignOffModelReleaseInput = {
    releaseId: request.params.releaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.clinicalSignoffs.get.execute(input);
  return reply.code(200).send(result);
}


