/**
 * Handlers for ModelRelease
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelReleasesDomainModule } from "../dependencies/model-releases-ddd.dependencies.js";
import type { CreateModelReleaseInput, GetModelReleaseInput, ListModelReleasesInput } from "@splitward/services/model-releases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/model-releases
 * Operation: listModelReleases
 */
export async function listModelReleases(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelReleasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListModelReleasesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.modelReleases.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/model-releases
 * Operation: createModelRelease
 */
export async function createModelRelease(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelReleasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateModelReleaseInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.modelReleases.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/model-releases/{releaseId}
 * Operation: getModelRelease
 */
export async function getModelRelease(
  request: FastifyRequest<{ Params: { releaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelReleasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetModelReleaseInput = {
    releaseId: request.params.releaseId,
  };
  const result = await deps.useCases.modelReleases.get.execute(input);
  return reply.code(200).send(result);
}


