/**
 * Repository interface for AuditPack
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AuditPackEntity
} from "../models/audit-pack.entity.js";
import type {
  ListAuditPacksParams,
  AuditPack
} from "../types/index.js";
/**
 * AuditPackRepository Interface
 */
export interface AuditPackRepository extends CreateReadRepository<AuditPackEntity, AuditPack, string, ListAuditPacksParams> {

}
