/**
 * GetStudy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getStudy } from "@splitward/api-server/domains/studies/handlers";
import type { StudiesDDDDependencies } from "@splitward/api-server/domains/studies";
import { createStudy as createStudyEntity } from "@splitward/factories/studies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { STUDIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetStudy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StudiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StudiesDDDDependencies>(
      STUDIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createStudyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetStudy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { studyId: entity.id };

    await getStudy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetStudy.execute).toHaveBeenCalledWith(expect.objectContaining({ studyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { studyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetStudy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getStudy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
