/**
 * ListStudies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listStudies } from "@splitward/api-server/domains/studies/handlers";
import type { StudiesDDDDependencies } from "@splitward/api-server/domains/studies";
import { createStudy as createStudyEntity } from "@splitward/factories/studies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { STUDIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListStudies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StudiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StudiesDDDDependencies>(
      STUDIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createStudyEntity({ orgId }),
      createStudyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListStudies, "execute").mockResolvedValue(useCaseResult);

    await listStudies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListStudies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
