/**
 * AuditPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPack DTOs
 *
 * DDD: Application DTOs for AuditPack use cases.
 */

import type { GenerateAuditPackRequestInput, GetAuditPackParams, ListAuditPacksParams } from "@splitward/core/audit-packs/types";

export type ListAuditPacksInput = ListAuditPacksParams;

export type GenerateAuditPackInput = GenerateAuditPackRequestInput;

export type GetAuditPackInput = GetAuditPackParams;

export type ListAuditPacksOutput = {};

export type GenerateAuditPackOutput = {};

export type GetAuditPackOutput = {};
