/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * ContributionCredits Domain Use Cases
 * 
 * List of all use case names for the contribution-credits domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONTRIBUTIONCREDITS_USE_CASES = [
  "executeGetContributionCredit",
  "executeListContributionCredits",
  "executeRecordContributionCredit"
] as const;
