/**
 * Repository interface for Study
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  StudyEntity
} from "../models/study.entity.js";
import type {
  ListStudiesParams,
  Study
} from "../types/index.js";
/**
 * StudyRepository Interface
 */
export interface StudyRepository extends CreateReadRepository<StudyEntity, Study, string, ListStudiesParams> {

}
