/**
 * RightsExclusion Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RightsExclusionEntity } from "@splitward/core/rights-exclusions/models/index.js";
import { rightsExclusionsSchemas } from "@splitward/core/rights-exclusions";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rex";

export function createRightsExclusion(overrides: Partial<RightsExclusionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    exclusionId: overrides.exclusionId ?? `rex_${ulid().toLowerCase()}`,
    reason: overrides.reason ?? faker.lorem.word(),
    siteId: overrides.siteId ?? faker.string.uuid(),
    status: overrides.status ?? "requested",
    ...overrides,
  };

  return rightsExclusionsSchemas.RightsExclusion.parse(raw);
}

export function rightsExclusionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRightsExclusion(overrides));
}
