/**
 * Routes for Incident
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getIncident, listIncidents, openIncident } from "../handlers/incident.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function incidentRoutes(fastify: FastifyInstance) {
  // GET /v0/tenants/me/incidents (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/incidents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncidentsDependenciesForRequest();
        await listIncidents(request, reply, deps);
      });
    }
  );


  // POST /v0/tenants/me/incidents (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/incidents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncidentsDependenciesForRequest();
        await openIncident(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/incidents/{incidentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/incidents/:incidentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIncidentsDependenciesForRequest();
        await getIncident(request, reply, deps);
      });
    }
  );


}
