/**
 * AuditPacks DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPacks Domain Module - Composition root
 *
 * DDD: Composition root for audit-packs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditPackRepositoryAdapter,
} from "@splitward/adapters/audit-packs";
import { getIdGeneratorService } from "@splitward/adapters";
import type { AdapterDynamoDBClient } from "@splitward/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGenerateAuditPack,
  ExecuteGetAuditPack,
  ExecuteListAuditPacks,
} from "@splitward/services/audit-packs/usecases";
// Ports (interfaces)
import type {
  AuditPackRepository,
} from "@splitward/services/audit-packs/ports";

export interface AuditPacksDomainModule {
  repos: {
    auditPacks: AuditPackRepository;
  };
  useCases: {
    auditPacks: {
      get: ExecuteGetAuditPack;
      list: ExecuteListAuditPacks;
    };
  };
}

export function buildAuditPacksDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditPacksDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      auditPacks?: AuditPackRepository;
    } = {};

    obj.auditPacks = new AuditPackRepositoryAdapter(dynamoClient);
    return {
      auditPacks: obj.auditPacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    auditPacks: {
      get: new ExecuteGetAuditPack(executionContext, idGenerator, repos.auditPacks),
      list: new ExecuteListAuditPacks(executionContext, idGenerator, repos.auditPacks),
    },
  };
  return { repos, useCases: useCases as AuditPacksDomainModule["useCases"] };
}
