/**
 * GetModelRelease DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetModelReleaseParams } from "@splitward/core/model-releases";

export function createGetModelReleaseRequest(overrides: Partial<GetModelReleaseParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
