/**
 * ContributionCreditRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contribution-credits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionCreditRepository Port
 *
 * DDD: Application port for contributioncreditrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetContributionCreditInput, GetContributionCreditOutput, ListContributionCreditsInput, ListContributionCreditsOutput, RecordContributionCreditInput, RecordContributionCreditOutput } from "../dto/contribution-credit.dto";
export interface ContributionCreditRepository {
  listContributionCredits(input: ListContributionCreditsInput): Promise<ListContributionCreditsOutput>;
  recordContributionCredit(input: RecordContributionCreditInput): Promise<RecordContributionCreditOutput>;
  getContributionCredit(input: GetContributionCreditInput): Promise<GetContributionCreditOutput>;
}

export type { GetContributionCreditInput, GetContributionCreditOutput, ListContributionCreditsInput, ListContributionCreditsOutput, RecordContributionCreditInput, RecordContributionCreditOutput } from "../dto/contribution-credit.dto";
