/**
 * Repository interface for RightsExclusion
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: rights-exclusions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RightsExclusionEntity
} from "../models/rights-exclusion.entity.js";
import type {
  ListRightsExclusionsParams,
  RightsExclusion
} from "../types/index.js";
/**
 * RightsExclusionRepository Interface
 */
export interface RightsExclusionRepository extends CreateReadRepository<RightsExclusionEntity, RightsExclusion, string, ListRightsExclusionsParams> {

}
