/**
 * ApprovePrivacyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApprovePrivacyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApprovePrivacyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApprovePrivacyRepository,
} from "@splitward/services/studies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApprovePrivacyRepositoryDdb } from "./approve-privacy-repository.ddb.js";

/**
 * ApprovePrivacyRepositoryAdapter
 *
 * Implements ApprovePrivacyRepository port for infrastructure layer.
 */
export class ApprovePrivacyRepositoryAdapter implements ApprovePrivacyRepository {
  private readonly ddb: ApprovePrivacyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApprovePrivacyRepositoryDdb(this.dynamoClient);
  }

  async approveStudyPrivacy(input: Parameters<ApprovePrivacyRepository['approveStudyPrivacy']>[0]): Promise<Awaited<ReturnType<ApprovePrivacyRepository['approveStudyPrivacy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveStudyPrivacy(input);
  }
}
