/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-privacy-repository.ddb.js";
export * from "./study-repository.ddb.js";
export * from "./submit-privacy-repository.ddb.js";
export * from "./approve-privacy-repository.adapter.js";
export * from "./study-repository.adapter.js";
export * from "./submit-privacy-repository.adapter.js";
