/**
 * SubmitPrivacyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitPrivacyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubmitPrivacyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubmitPrivacyRepository,
} from "@splitward/services/studies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubmitPrivacyRepositoryDdb } from "./submit-privacy-repository.ddb.js";

/**
 * SubmitPrivacyRepositoryAdapter
 *
 * Implements SubmitPrivacyRepository port for infrastructure layer.
 */
export class SubmitPrivacyRepositoryAdapter implements SubmitPrivacyRepository {
  private readonly ddb: SubmitPrivacyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubmitPrivacyRepositoryDdb(this.dynamoClient);
  }

  async submitStudyForPrivacy(input: Parameters<SubmitPrivacyRepository['submitStudyForPrivacy']>[0]): Promise<Awaited<ReturnType<SubmitPrivacyRepository['submitStudyForPrivacy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitStudyForPrivacy(input);
  }
}
