/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: model-releases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { clinicalSignoffRoutes } from "./clinical-signoff.routes.js";
export { modelReleaseRoutes } from "./model-release.routes.js";
