/**
 * Study Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { StudyEntity } from "@splitward/core/studies/models/index.js";
import { studiesSchemas } from "@splitward/core/studies";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "stu";

export function createStudy(overrides: Partial<StudyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    privacyApprovalStatus: overrides.privacyApprovalStatus ?? "pending",
    status: overrides.status ?? "draft",
    strategy: overrides.strategy ?? "split",
    studyId: overrides.studyId ?? `stu_${ulid().toLowerCase()}`,
    title: overrides.title ?? faker.lorem.sentence(),
    ...overrides,
  };

  return studiesSchemas.Study.parse(raw);
}

export function studyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createStudy(overrides));
}
