/**
 * GetTrainingRound handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training-rounds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTrainingRound } from "@splitward/api-server/domains/training-rounds/handlers";
import type { TrainingRoundsDDDDependencies } from "@splitward/api-server/domains/training-rounds";
import { createTrainingRound as createTrainingRoundEntity } from "@splitward/factories/training-rounds";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@splitward/tests/shared";
import { TRAININGROUNDS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTrainingRound", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TrainingRoundsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TrainingRoundsDDDDependencies>(
      TRAININGROUNDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTrainingRoundEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTrainingRound, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { roundId: entity.id };

    await getTrainingRound(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTrainingRound.execute).toHaveBeenCalledWith(expect.objectContaining({ roundId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { roundId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTrainingRound, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTrainingRound(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
