/**
 * Routes for AuditPack
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { generateAuditPack, getAuditPack, listAuditPacks } from "../handlers/audit-pack.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function auditPackRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/audit-packs (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/audit-packs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditPacksDependenciesForRequest();
        await generateAuditPack(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/audit-packs (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/audit-packs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditPacksDependenciesForRequest();
        await listAuditPacks(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/audit-packs/{packId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/audit-packs/:packId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditPacksDependenciesForRequest();
        await getAuditPack(request, reply, deps);
      });
    }
  );


}
