/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: studies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Studies Domain Use Cases
 * 
 * List of all use case names for the studies domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const STUDIES_USE_CASES = [
  "executeApproveStudyPrivacy",
  "executeCreateStudy",
  "executeGetStudy",
  "executeListStudies",
  "executeSubmitStudyForPrivacy"
] as const;
